# Generated by Django 6.0.4 on 2026-04-30 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(default='Sri Lanka', max_length=100)),
                ('description', models.TextField()),
                ('image_url', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('Nature', 'Nature'), ('Culture', 'Culture'), ('Temple', 'Temple'), ('Beach', 'Beach'), ('Adventure', 'Adventure'), ('Food', 'Food'), ('History', 'History'), ('Wildlife', 'Wildlife')], default='Nature', max_length=50)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_featured', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TripPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=200)),
                ('destination_city', models.CharField(max_length=200)),
                ('destination_country', models.CharField(default='Sri Lanka', max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('interests', models.CharField(max_length=500)),
                ('budget', models.IntegerField()),
                ('travel_mode', models.CharField(choices=[('Car', 'Car'), ('Bus', 'Bus'), ('Train', 'Train')], default='Car', max_length=20)),
                ('plan_json', models.JSONField()),
                ('weather_summary', models.CharField(blank=True, max_length=500)),
                ('map_url', models.URLField(blank=True, max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
