# Generated by Django 5.2.3 on 2026-05-16 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='accommodation_type',
            field=models.CharField(blank=True, choices=[('Luxury', 'Luxury Hotel'), ('Budget', 'Budget / Hostel'), ('Homestay', 'Homestay'), ('EcoFriendly', 'Eco-Friendly Lodge'), ('Camping', 'Camping')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='food_interests',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_activities',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
