# Generated by Django 6.0.4 on 2026-05-20 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripplan',
            name='accommodation_preferences',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='tripplan',
            name='activity_preferences',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='tripplan',
            name='food_preferences',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='accommodation_preferences',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='activity_preferences',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='food_preferences',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
