# Generated by Django 5.2.3 on 2026-05-20 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_userprofile_accommodation_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='accommodation_type',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='food_interests',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='preferred_activities',
        ),
        migrations.AddField(
            model_name='tripplan',
            name='accommodation_preferences',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='tripplan',
            name='activity_preferences',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='tripplan',
            name='food_preferences',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='accommodation_preferences',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='activity_preferences',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='food_preferences',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
